[project]
name = "sns-discord"
version = "0.1.0"
requires-python = ">=3.13"

[dependency-groups]
dev = ["boto3"]
grafana-github = [
  "pygithub>=2.10.0",
]
lint = [
  "ruff==0.16.9",
  "ty==0.0.84",
]
mastodon-boost = [
  "mastodon-py>=2.2.2",
]
mastodon-discord = [
  "html2text>=2025.4.15",
  "mastodon-py>=2.2.2",
  "requests>=2.34.2",
]
sns-discord = [
  "hgtk>=0.2.1",
]

[tool.uv]
default-groups = [
  "dev",
  "grafana-github",
  "mastodon-boost",
  "mastodon-discord",
  "sns-discord",
]

[tool.ruff.lint]
extend-select = [
  "B",
  "BLE",
  "C901",
  "FURB",
  "I",
  "PERF",
  "PIE",
  "PLR0912",
  "PLR0913",
  "PLR0915",
  "RET",
  "SIM",
  "TRY",
  "UP",
]
