on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - run: rustup target add x86_64-unknown-linux-musl
    - name: Cache toolchains
      uses: actions/cache@v2
      with:
        path: |
          ~/.rustup/settings.toml
          ~/.rustup/toolchains
          ~/.rustup/update-hashes
        key: toolchains-${{ runner.os }}

    - uses: actions/checkout@v2
    - run: cargo fmt --all -- --check

    - run: cargo build --release && zip -j lambda.zip target/x86_64-unknown-linux-musl/release/bootstrap
    - name: Cache crates
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git
        key: crates-${{ runner.os }}

    - run: cargo test
    - run: cargo clippy -- -D warnings

    - name: Cache build results
      uses: actions/cache@v2
      with:
        path: ./target
        key: build-${{ hashFiles('Cargo.lock') }}
