on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Cache toolchains and crates
      uses: actions/cache@v2
      with:
        path: |
          ~/.rustup/settings.toml
          ~/.rustup/toolchains
          ~/.rustup/update-hashes
          ~/.cargo/registry
          ~/.cargo/git
        key: toolchains-and-crates-${{ runner.os }}

    - uses: actions/checkout@v2

    - name: Cache build results
      uses: actions/cache@v2
      with:
        path: |
          target
        key: build-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

    - run: rustup target add x86_64-unknown-linux-musl
    - run: sudo apt-get install musl-tools
    - run: cargo fmt --all -- --check
    - run: cargo build --release && zip -j lambda.zip target/x86_64-unknown-linux-musl/release/sns-discord
    - run: cargo test
    - run: cargo clippy -- -D warnings

